tareas:
  -ver que sacar de de las paginas
  -ver las tablas a utilizar

  @started(16-02-17 21:38)
  merton y shon premio nobel de economia
  http://15.idea.lanyus.com
  
  -activar tarjeta de credito

  -ver base de datos,             @started(16-02-27 15:23)
      *backup de todal la base de datos 
  -que necesito de en el sistema  @started(16-02-27 15:23)
  -ocultar lo que no necesito     @started(16-02-27 15:23)


codigo suig famipypa
citybaca