<?php

/**
 * Created by PhpStorm.
 * User: alberto
 * Date: 31/03/16
 * Time: 07:10 AM
 */
class mi_pagina extends fs_controller
{
    public $variable;
    public function __construct()
    {
        parent::__construct(__CLASS__,'mi pagina','informes');
    }
    protected function private_core()
    {
        $this->variable=array(
            'manzanas'=>array('color'=>'rojas', 'peso'=>'200'),
            'peras'=>array('color'=>'amarillo', 'peso'=>'100'),
            'piñas'=>array('color'=>'marron', 'peso'=>'300'),
        );
//        parent::private_core(); // TODO: Change the autogenerated stub
    }

}